### PR TITLE
a rewrite of the Julia side to use StaticLint.jl

### LINKED ISSUE #12: Implementing StaticLint.jl
https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/33

### PR DESCRIPTION
**Pull request by takbal**
This is a fork that replaces Lint.jl with StaticLint.jl. It seems to work for me, but could use more testing.

Please check the readme for changes and caveats.

Technical details:

From 956971b it is an almost complete rewrite to use a single server process. Julia is quite a heavy thing to run one for each editor, and I have decided that it is more important to keep resources low than being just a bit faster. Perhaps it could be still parallelised further by running a dedicated pipe for each editor, rather sharing a single pipe like now, but I feel the speed is already adequate, especially considering that the bottleneck is the symbol server building anyway (that is already spawning in a separate thread).

I still see some problem with lints at end of line being dragged around if enter is pressed on it, but this looks like happening with eslint too, so probably it is an issue with linter.

I know almost nothing of Atom development or js, so the changes are likely ugly there, please revise. I could not make Atom to shut down the child process, so the server exits by polling Atom's PID right now.

Fixes #12

### CODE REVIEW

**Comment by aminya** [comment]
Could you fix the CI as well? Unfortunately, this organization is a closed access organization, and even though I have write-access, I cannot merge this pull request.
https://github.com/AtomLinter/linter-eslint/issues/1383

If you can fix the CI somehow, I will merge it.

@Arcanemagus

**Comment by takbal** [comment]
I have an improved version now that does on-the-fly linting, and uses only a single server. Still has to somehow kill the process on the Windows side on shutdown. Will try to fix the CI.

**Comment by takbal** [comment]
@aminya all done now: single server, dynamic linting, works on Windows, even that crude unit test passes. Please merge if you can.

**Review by aminya — APPROVED** [review]
Thanks for this awesome work!

**Comment by takbal** [comment]
@aminya Thanks!

Perhaps making a new release would be nice, so it shows up in the official repos. The README should be changed accordingly, like removing the ref to my fork.

About help: absolutely, this effort could clearly benefit from a js/Atom expert like yourself - I have just butchered the. js scripts without any real knowledge of how it should be done. Please modify as you wish - I have no big plans on working on it further, unless it breaks.

**Comment by takbal** [comment]
Oh you did it already while I was typing, awesome.

**Comment by aminya** [comment]
@takbal Thank you! 

I will dive into the code once I find some free time in the future. I am planning on making a full-fledged ide-julia based on LSP to consolidate all the code into one all-around package. But for now, the good thing is that the linter works!

**Pull request merged**
